### ISSUE TITLE
pip build can't find README.rst

### ISSUE THREAD

**Issue by JeffCarpenter** [vinay20045/json-to-csv#7]
When I try to install via pip I get a file not found error for README.rst:

```bash
pip install json-to-csv
Collecting json-to-csv
  Using cached json_to_csv-1.2.9.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4l/9j724xnn16s2s1bhv9_7l_v00000gn/T/pip-build-0AJu9Q/json-to-csv/setup.py", line 22, in <module>
        with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 896, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/private/var/folders/4l/9j724xnn16s2s1bhv9_7l_v00000gn/T/pip-build-0AJu9Q/json-to-csv/README.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/4l/9j724xnn16s2s1bhv9_7l_v00000gn/T/pip-build-0AJu9Q/json-to-csv/```

**Comment by vinay20045** [comment]
The one you are trying to install via pip is not this particular library. Please check PyPI and contact the concerned author...

I have not yet come around to making my script a library (Ref #6). You have to take the code and modify it a bit to use it as a library :(
